export {
  loginSchema,
  signupSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  accountTypeSchema,
  basicInfoSchema,
  studentInfoSchema,
  companyRepInfoSchema,
  facultyInfoSchema,
  userTypeSchema,
  type LoginFormData,
  type SignupFormData,
  type ForgotPasswordFormData,
  type ResetPasswordFormData,
  type AccountTypeFormData,
  type BasicInfoFormData,
  type StudentInfoFormData,
  type CompanyRepInfoFormData,
  type FacultyInfoFormData,
  type UserType,
} from "./authSchemas";
