const UniversityList = [
        "Cairo University",
        "Ain Shams University",
        "Helwan University",
	"Al-Azhar University",
        "American University in Cairo",
        "British University in Egypt",
        "German University in Cairo",
	"Arab Academy for Science, Technology and Maritime Transport",
        "Misr International University",
        "October 6 University",
	"MSA University",
	"Ahram Canadian University",
	"Nile University",
	"Zewail City of Science and Technology",
	"New Giza University",
        "Future University in Egypt",
	"The Knowledge Hub",
	"German International University",
        "Alexandria University",
	"Fayoum University",
        "Mansoura University",
	"Menoufia University",
        "Zagazig University",
	"University of Sadat City",
	"Tanta University",
	"Suez University",
        "Other"
];
export default UniversityList;