import {
  LoginPage,
  SignupPage,
  SignupConfirmation,
  ForgotPasswordPage,
  AboutUsPage,
  EventsPage,
  EventDetailsPage,
  PastEventsPage,
  GalleryPage,
  GalleryDisplayPage,
  ProfilePage,
  EventTicketPage,
  OTPPage, 
  QRScannerPage,
  LocationsManagementPage,
  PostManagementPage,
  EventRegistrationPage,
  EventsAdminPage,
  StatisticsPage,
  HomePage,
  PostPage,
} from "@/features";

export const routes = [
  { path: "/", Component: HomePage },
  { path: "/login", Component: LoginPage },
  { path: "/sign-up", Component: SignupPage },
  { path: "/sign-up/confirmation", Component: SignupConfirmation },
  { path: "/forgot-password", Component: ForgotPasswordPage },
  { path: "/aboutus", Component: AboutUsPage },
  { path: "/events/:id", Component: EventDetailsPage },
  { path: "/events", Component: EventsPage },
  { path: "/past-events", Component: PastEventsPage },
  { path: "/gallery", Component: GalleryPage },
  { path: "/profile", Component: ProfilePage },
  { path: "/gallery/view/:id", Component: GalleryDisplayPage },
  { path: "/tickets/:id", Component: EventTicketPage },
  { path: "/otp", Component: OTPPage },
  { path: "/scan-qr", Component: QRScannerPage },
  { path: "/posts", Component: PostManagementPage },
  { path: "/posts/:id", Component: PostPage },
  { path: "/admin/locations", Component: LocationsManagementPage },
  { path: "/events/register/:id", Component: EventRegistrationPage },
  { path: "/admin/events", Component: EventsAdminPage }, // NOT A PROTECTED ROUTE, CAREFUL WITH INTEGRATION
  { path: "/admin/statistics", Component: StatisticsPage },
];
